# -*- coding: utf-8 -*-
"""Atividade 4 Algoritmos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAaiii5XKQ2xj_pgcpz5aeNMUPdoxNlp
"""

"""
BOOKS TO SCRAPE
===============
Atividade para extrair os dados de livros do site Books to Scrape e salvar em um arquivo CSV.
Gabriela Borba
10/09/2025
"""

!pip install requests beautifulsoup4

"""
IMPORTANDO AS BIBLIOTECAS
=========================
Requests: Para fazer as requisições HTTP e baixar a página;
BeaultifulSoup: Para extrair os dados da página;
Pandas: Para manipular os dados e salvar em um arquivo CSV.
"""
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL do site que será utilizado e a requisição HTTP para baixar a página
url = "https://books.toscrape.com/index.html"
resposta = requests.get(url)

# Parseando o HTML
sopa = BeautifulSoup(resposta.text, 'html.parser')

# Extraindo os dados
title = sopa.find_all("h3")
price = sopa.find_all("p", class_="price_color")
availability = sopa.find_all("p", class_="instock availability")

# Lista os dados para armazená-los
dados_livros = []

# Processa cada livro encontrato e combina três listas para iterar simultaneamente
for t, p, a in zip(title, price, availability):
  titulo = t.a['title'] # Extrai os títulos
  preco = p.text.replace('Â', '') # Extrai os preços e remove o caractere "Â"
  disponibilidade = a.text.strip() #  Extrai a disponibilidade (estoque) e remove espaços em branco
  print(f"Título: {titulo}\nPreço: {preco}\nDisponibilidade: {disponibilidade}\n")

  # Adiciona os dados à lista
  dados_livros.append({
      'Título': titulo,
      'Preço': preco,
      'Disponibilidade': disponibilidade
  })

# Cria um DataFrame com pandas
df = pd.DataFrame(dados_livros)

# Exporta para arquivo CSV
df.to_csv("livros.csv",
            index=False, # Não inclui a coluna de índice numérico
            encoding="utf-8-sig", # Resolve problemas com acentos no Excel
            columns=['Título', 'Preço', 'Disponibilidade']) # Especifica a ordem das colunas

# Download automático no Google Colab
from google.colab import files
files.download('livros.csv')